name: PSScriptAnalyzer
on: [push, pull_request]
jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        sendComment: true
        failOnErrors: true
        failOnWarnings: true
        failOnInfos: false
        settingsPath: .github/workflows/PSScriptAnalyzerSettings.psd1
        repoToken: ${{ secrets.GITHUB_TOKEN }}