name: PSScriptAnalyzer
on: [push, pull_request]
jobs:
  lint:
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        #rootPath: MyModule
        sendComment: true
        failOnErrors: true
        failOnWarnings: true
        failOnInfos: false
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        settingsPath: github/workflows/pssa_settings.psd1